version: "3.9"

services:
  etl_runner:
    build: .
    container_name: football_etl
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity

  postgres:
    image: postgres:15
    container_name: football_db
    environment:
      POSTGRES_DB: football
      POSTGRES_USER: football
      POSTGRES_PASSWORD: football
    ports:
      - "5432:5432"
